version: '3'

services:
  composer:
    volumes:
      - ./composer.json:/app/composer.json
      - ./composer.lock:/app/composer.lock
      - vendor:/app/vendor
      - web:/app/web
  db:
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
  vendor:
  web:
